language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcurl4-openssl-dev libjsoncpp-dev libargtable2-dev libboost-test-dev

compiler:
  - clang
  - gcc

script: mkdir -p build && cd build && cmake .. && make && make test
